[package]
name = "nuts"
version = "0.1.0"
authors = ["Jakob Meier <inbox@jakobmeier.ch>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"


[dependencies]


# Used for example only
# [dev-dependencies] Sadly, cargo-web cannot run the example with dev-dependecies only...
[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.20"